server:
  port: 9112

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/DB_Employee
    username: postgres
    password: Support1
  liquibase:
    enabled: 'true'
    drop-first: 'true'
    change-log: classpath:/db/changelog/changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: create